apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/g33ta/flask_home_ecs:~1
    #argocd-image-updater.argoproj.io/argocd.kustomize.image-name: nginx
spec:
  project: default

  source:
    repoURL: https://github.com/g33ta/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/staging/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
